#!/usr/bin/env sh

# Load the husky script
. "$(dirname -- "$0")/_/husky.sh"

# Check for changes in the backend directory
if ! git diff --quiet HEAD HEAD~ -- backend; then
  echo "Changes detected in backend. Running format..."
  cd backend
  npm run format
  cd ..
fi

# Check for changes in the frontend directory
if ! git diff --quiet HEAD HEAD~ -- frontend; then
  echo "Changes detected in frontend. Running lint..."
  cd frontend
  npm run lint
  cd ..
fi